### ISSUE TITLE
Add labels support to BigQuery query runner

### ISSUE THREAD

**Issue by jasonthomas** [mozilla/redash-stmo#30]
To better understand our BigQuery usage it would be great if we could make uses of BigQuery query job labels when making requests to BigQuery [1][2]

At a minimum I think we need to have two labels:
* Owner - the email address or user name of the creator of the query
* Name - some unique identifier for the query - it could probably just be the query id

[1] https://docs.google.com/document/d/1xpA6H0kRDuMZr2f6RPZUlHu-YQylbmMRiK2RrtnZiwM/edit
[2] https://cloud.google.com/bigquery/docs/adding-using-labels#job-label

**Comment by jezdez** [comment]
Together with https://github.com/mozilla/redash/issues/835 and https://github.com/mozilla/redash/issues/836 I think we may want to have an own Big Query query runner to do such things.

**Comment by jezdez** [comment]
I've opened https://github.com/getredash/redash/pull/3742 and also opened https://github.com/mozilla/redash/pull/945 while we wait for upstream to merge and us rebase on top of it.

**Comment by jezdez** [comment]
Nice, upstream got merged already.

**Comment by jezdez** [comment]
@jasonthomas This was sidetracked a bit, but this is being developed in #38.

**Comment by jezdez** [comment]
This was done in #38. @jasonthomas Do you need to do anything on your side to prepare BQ?

**Comment by jasonthomas** [comment]
No additional changes need to be made on BQ AFAIK.

**Comment by jezdez** [comment]
Huzzah! 🎉
