### ISSUE TITLE
Unable to add or manage Presto datasource in Redash UI

### ISSUE THREAD

**Issue by jasonthomas** [mozilla/redash-stmo#33]
STR:

* Visit https://pipeline-sql.stage.mozaws.net/data_sources
* Select 'New Data Source'
* Select 'STMOPresto'
* New page loads with no text input fields.

**Comment by jezdez** [comment]
Hm, can't reproduce this, the form correctly renders for me:

<img width="760" alt="Screen-Shot-2019-04-03-09-30-38 62" src="https://user-images.githubusercontent.com/1610/55460804-30768b80-55f3-11e9-9b5e-8edf977b227b.png">

**Comment by jezdez** [comment]
Seems like @washort has fixed it upstream in https://github.com/mozilla/redash/commit/7920515da6d660f07189e06afb79bd002c12c55f.
